management:
  endpoints:
    web:
      exposure:
        include: "*"

redis:
    hostname: localhost
    port: 6379

msgman:
  producer:
    enabled: true
    name: randomMsg
    chance: 90
    sleep: 100
  consumer:
    enabled: true
