apiVersion: v1
kind: Service
metadata:
  name: svc-for-prom
  labels:
    app: msgman
spec:
  selector:
    app: msgman
  ports:
    - protocol: TCP
      name: http-traffic
      port: 8080
      targetPort: 8080

---      
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: msgman-service-monitor
spec:
  selector:
    matchLabels:
      app: msgman
  endpoints:
  - port: http-traffic
    path: "/actuator/prometheus"